title: We finally found Qachalnoc.
email: tigran@qachal.tk
description: This will make you QACHAL. Every day.
facebook_username: tigran93

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
